-- FACT CUSTOMER PURCHASED
{{ config (materialized = "table") }}
SELECT 
A.CUSTOMER_ID 
, B.CUSTOMER_NAME
,COUNT(A.CUSTOMER_ID)TOTAL_ITEMS_PURCHASED
,SUM(A.TOTAL_AMOUNT) TOTAL_AMOUNT_SPEND
FROM {{ ref('DIM_ORDERS') }} A
INNER JOIN {{ ref('DIM_CUSTOMERS') }} B ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY 1,2